# Generated by Django 4.2.2 on 2023-06-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='views',
            options={'verbose_name_plural': 'Views'},
        ),
    ]
