# Generated by Django 4.2.2 on 2023-06-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0002_alter_profile_cover_photo_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default=1, upload_to='cover_photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=0.043478260869565216, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
