# Generated by Django 4.2.2 on 2023-06-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_video', '0002_channel_channel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='video',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='subsciber',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
