# Generated by Django 4.2.2 on 2023-06-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_video', '0003_remove_like_user_remove_like_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='public_view',
            field=models.BooleanField(default=True),
        ),
    ]
